import { MainWalletBase } from '@cosmos-kit/core';
export declare type WalletName = 'keplr' | 'cosmostation' | 'ledger' | 'okxwallet' | 'station' | 'leap' | 'trust' | 'xdefi' | 'vectis' | 'frontier' | 'fin' | 'omni' | 'coin98' | 'shell' | 'compass' | 'tailwind' | 'owallet' | 'exodus' | 'galaxystation' | 'cosmjs';
export declare type WalletList<E extends MainWalletBase | null, M extends MainWalletBase | null> = (E extends MainWalletBase ? M extends MainWalletBase ? [E, M] : [E] : M extends MainWalletBase ? [M] : []) & {
    mobile: M | null;
    extension: E | null;
};
export declare function createWalletList<ExtensionWallet extends MainWalletBase | null, MobileWallet extends MainWalletBase | null, MetaMaskSnap extends MainWalletBase | null>(extension: ExtensionWallet | null, mobile: MobileWallet | null, snap?: MetaMaskSnap): WalletList<ExtensionWallet, MobileWallet>;
export declare const keplr: WalletList<any, any>;
export declare const cosmostation: WalletList<any, any>;
export declare const ledger: any;
export declare const leap: WalletList<any, any>;
export declare const station: WalletList<any, any>;
export declare const okxwallet: WalletList<any, any>;
export declare const trust: WalletList<any, any>;
export declare const xdefi: WalletList<any, any>;
export declare const vectis: WalletList<any, any>;
export declare const frontier: WalletList<any, any>;
export declare const fin: WalletList<any, any>;
export declare const omni: WalletList<any, any>;
export declare const shell: WalletList<any, any>;
export declare const coin98: WalletList<any, any>;
export declare const compass: WalletList<any, any>;
export declare const exodus: WalletList<any, any>;
export declare const tailwind: WalletList<any, any>;
export declare const owallet: WalletList<any, any>;
export declare const galaxystation: WalletList<any, any>;
export declare const cosmjs: WalletList<any, any>;
export declare type SubWalletList = MainWalletBase[] & {
    get mobile(): MainWalletBase[];
    get extension(): MainWalletBase[];
};
export declare type AllWalletList = SubWalletList & {
    keplr: typeof keplr;
    cosmostation: typeof cosmostation;
    ledger: typeof ledger;
    okxwallet: typeof okxwallet;
    station: typeof station;
    leap: typeof leap;
    trust: typeof trust;
    xdefi: typeof xdefi;
    vectis: typeof vectis;
    frontier: typeof frontier;
    fin: typeof fin;
    omni: typeof omni;
    coin98: typeof coin98;
    compass: typeof compass;
    exodus: typeof exodus;
    tailwind: typeof tailwind;
    owallet: typeof owallet;
    galaxystation: typeof owallet;
    cosmjs: typeof cosmjs;
    for: (...names: WalletName[]) => SubWalletList;
    not: (...names: WalletName[]) => SubWalletList;
};
export declare function defineGetters(wallets: MainWalletBase[]): SubWalletList;
export declare function createAllWalletList(ws: MainWalletBase[]): AllWalletList;
export declare const wallets: AllWalletList;
